import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ART from "data/art.json";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto w-full max-w-screen-lg">
        {/* TODO: Show the 4 pieces of art along with their details */}
        <h1>Example App</h1>
        <form>
          {/* TODO: Filter art */}
          <input type="search" placeholder="Search…" className="border" />
        </form>
        <ul>{/* TODO: List of art */}</ul>
      </main>
    </>
  );
};

export default Home;
